---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
commonLabels:
  app.kubernetes.io/env: staging
resources:
  - ./podinfo/
<<<<<<< HEAD
  - ./../../../base/debug/
=======
>>>>>>> 344d5d9 (feat: 添加 K8S 生产集群)
