---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k3s-test-1-master-1
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: s-2vcpu-2gb
  template:
    metadata:
      labels:
        kubevirt.io/vm: k3s-test-1-master-1
    spec:
      volumes:
        - dataVolume:
            name: k3s-test-1-master-1-disk
          name: rootdisk
  dataVolumeTemplates:
    - metadata:
        name: k3s-test-1-master-1-disk
      spec:
        pvc:
          # this is the rootdisk of the node, it contains critical data
          storageClassName: local-path-critical
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          # NOTE: lock down the volume name to avoid creating a new one
          # This should only be used when you want to reuse the volume(like recreating the VM).
          # volumeName: ''
        source:
          http:
            url: http://file.slk.moe/vms/K3S-Test-1-Master-1.qcow2
            certConfigMap: "ca.crt"
