
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-namespaces
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 10s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/namespaces
  # NOTE: Namespaces are very likely to have stateful resources that
  # will prevent deletion if they are not empty.
  # So, we should not prune them automatically!
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-namespaces
  interval: 1h
  retryInterval: 10s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/controllers/overlays/k3s-prod-1
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 10s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/configs/overlays/k3s-prod-1
  prune: true