---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: k3s-prod-1-worker-3
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: s-2vcpu-2gb
  template:
    metadata:
      labels:
        kubevirt.io/vm: k3s-prod-1-worker-3
    spec:
      volumes:
        - dataVolume:
            name: k3s-prod-1-worker-3-disk
          name: rootdisk
  dataVolumeTemplates:
    - metadata:
        name: k3s-prod-1-worker-3-disk
      spec:
        pvc:
          # this is the rootdisk of the node, it contains critical data
          storageClassName: local-path-critical
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          # NOTE: lock down the volume name to avoid creating a new one
          # This should only be used when you want to reuse the volume(like recreating the VM).
          # volumeName: ''
        source:
          http:
            url: http://file.slk.moe/vms/K3S-Prod-1-Worker-3.qcow2
            certConfigMap: "ca.crt"
